version: '3.1'

services:
  mysql:
    image: mysql
    expose: 
        - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - ./DataBase/mysql_data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: grupo17
    ports:
      - "3036:3306"
  
  #server1:
    #image: server1
    #build:
      #dockerfile: Dockerfile
      #context: ./Servidor1
    #ports:
      #- "3001:3001"

  #server2:
    #image: server2
    #build:
      #dockerfile: Dockerfile
      #context: ./Servidor2
    #ports:
      #- "3002:3002"

  #server3:
    #image: server3
    #build:
      #dockerfile: Dockerfile
      #context: ./Servidor3
    #ports:
      #- "3003:3003"
