version: '3.1'

services:
  bd:
    image: mysql
    container_name: bd
    command: --default-authentication-plugin=mysql_native_password
    expose: 
      - "3306"
    restart: always
    volumes:
      - ./DataBase/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: grupo17
    networks:
      - db_network
      
  
  server1:
    image: server1
    container_name: server1
    build:
      dockerfile: Dockerfile
      context: ./Servidor1
    depends_on:
      - bd
    networks:
        - db_network
        - service_network

  server2:
    image: server2
    container_name: server2
    build:
      dockerfile: Dockerfile
      context: ./Servidor2
    depends_on:
      - bd
    networks:
      - db_network
      - service_network


  server3:
    image: server3
    container_name: server3
    build:
      dockerfile: Dockerfile
      context: ./Servidor3
    depends_on:
      - bd
    networks:
      - db_network
      - service_network

  loadbalancer:
    image: nginx  
    container_name: loadbalancer
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - server1
        - server2
        - server3
    networks:
        - service_network
        - frontend_network
            
networks:
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.17.0/24
  
  service_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.77.0/24
  
  frontend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.57.0/24
