version: '3.5'

services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ~/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: grupo17
    networks:
      - db_network
      
  
  server1:
    image: server1
    container_name: server1
    #restart: always
    environment:
      - Signature=201503470
      - PORT=80
    build:
      dockerfile: Dockerfile
      context: ./Backend
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - db_network
      - service_network
    

  server2:
    image: server2
    container_name: server2
    environment:
      - Signature=201246079
      - PORT=80
    build:
      dockerfile: Dockerfile
      context: ./Backend
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - db_network
      - service_network


  server3:
    image: server3
    container_name: server3
    environment:
      - Signature=201709164
      - PORT=80
    build:
      dockerfile: Dockerfile
      context: ./Backend
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - db_network
      - service_network

  loadbalancer:
    image: nginx  
    container_name: loadbalancer
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - server1
        - server2
        - server3
    networks:
        - service_network
        - frontend_network
  
  frontend:
    image: frontend
    container_name: frontend
    environment:
      - Signature=201709164
    build:
      dockerfile: Dockerfile
      context: ./front-grupo17
    #volumes:
    #  - ./front-grupo17/dist/front-grupo17:/usr/share/nginx/html
    depends_on:
      - loadbalancer
    links:
      - "loadbalancer"
    networks:
      - frontend_network
            
networks:
  db_network:
    driver: bridge
    name: db_network
    ipam:
      config:
        - subnet: 10.10.17.0/24
  
  service_network:
    driver: bridge
    name: service_network
    ipam:
      config:
        - subnet: 172.35.77.0/24
  
  frontend_network:
    driver: bridge
    name: frontend_network
    ipam:
      config:
        - subnet: 192.168.57.0/24
